### PR TITLE
Typechecker declaration graph + rec-rule

### PR DESCRIPTION
**Pull request by SebastianMestre**
I have implemented the rec rule.

~There is no testing so it might not be a good idea to merge it just yet...~

### CODE REVIEW

**Comment by lushoBarlett** [comment]
I don't think I quite get the purpose of this 'hidden type vars' as dummies. Would you mind explaining a little bit to me what that's all about?

**Comment by SebastianMestre** [comment]
> I don't think I quite get the purpose of this 'hidden type vars' as dummies. Would you mind explaining a little bit to me what that's all about?

Hidden type vars are type vars that get generalized no matter what. (Because they are never added to the context)

We give a dummy type var to every declaration in the rec-block because they need to have a type, because they will be referenced by some other declaration within the same rec-block, before they are typechecked.

**Comment by SebastianMestre** [comment]
I just fixed some bugs and added a test. I am pretty confident it works now.

**Review by lushoBarlett — APPROVED** [review]
I'm not that close to the type system, but I did _kind of_ understand how this works. Anyhow, the tests actually working are more that enough for me to approve this pr. Great stuff!

**Pull request merged**
