### PR TITLE
Optimize argument passing

### PR DESCRIPTION
**Pull request by SebastianMestre**
I figured we don't really need to put arguments in a vector before we pass them. So, I am trying to make it so.

### CODE REVIEW

**Comment by SebastianMestre** [comment]
I haven't managed to get rid of the vector yet, but I did simplify some things, and it did get faster.

**Comment by SebastianMestre** [comment]
Second round of measurements:



before (master) (30 runs):

    0,114305 +- 0,000115 seconds time elapsed ( +- 0,10% )

before (round 1 on this pr) (30 runs):

    0,104121 +- 0,000782 seconds time elapsed ( +- 0,75% )

now (30 runs):

    0,091157 +- 0,000209 seconds time elapsed  ( +-  0,23% )

overall improvement: 20.25%

**Comment by SebastianMestre** [comment]
Funnily enough, If you take out `Span`, the change to `gc_ptr`, and the extra line in the Makefile, this is actually 1 line shorter

**Review by lushoBarlett — APPROVED** [review]
This is a clever approach, I think what it does is:

The call expression pushes the arguments, then the function itself already points to those locations. That saves a whole vector every function.

Cool stuff!

**Pull request merged**
