### PR TITLE
implement stack-based local variables

### PR DESCRIPTION
**Pull request by SebastianMestre**
I figured that, instead of spending more work on optimizing the dictionary in Interpreter::Environment, we should do something to forego it entirely, just like in compiled languages.

This is a first pass on that concept.

### CODE REVIEW

**Comment by SebastianMestre** [comment]
For now, we still need to build the scope stack because this doesnt handle captures. Handling captures is what comes next.

Once we handle captures, we no longer need a scope stack, just a single global scope.

After that, we can expand this to work with globals, too. At that point, we could get rid of Interpreter::Scope entirely.

**Comment by SebastianMestre** [comment]
It's essentially working now

**Comment by SebastianMestre** [comment]
It still has a very 'hacked-on' feeling to it, so it needs more clean up, but I think this is pretty good, I'll run some benchmarks tomorrow.

**Comment by SebastianMestre** [comment]
I just measured, I observed an 18% decrease in mean execution time (standard deviation is about 0.1%)

**Comment by SebastianMestre** [comment]
This actually opens up some changes that could be done to simplify and optimize the runtime even more, but this is already a pretty large patch.

**Review by lushoBarlett — APPROVED** [review]
Looks fine to me, honestly

**Pull request merged**
